# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yelp}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Dan Engle}]
  s.date = %q{2011-06-06}
  s.description = %q{The yelp rubygem provides a Ruby object-oriented interface to the Yelp.}
  s.email = %q{dengle@localoffernetwork.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
    "LICENSE.txt",
    "Manifest",
    "Manifest.txt",
    "README.rdoc",
    "Rakefile",
    "TODO.txt",
    "VERSION",
    "lib/yelp.rb",
    "lib/yelp/client.rb",
    "lib/yelp/neighborhood/request/base.rb",
    "lib/yelp/neighborhood/request/geo_point.rb",
    "lib/yelp/neighborhood/request/location.rb",
    "lib/yelp/phone/request/number.rb",
    "lib/yelp/record.rb",
    "lib/yelp/request.rb",
    "lib/yelp/response_format.rb",
    "lib/yelp/review/request/base.rb",
    "lib/yelp/review/request/bounding_box.rb",
    "lib/yelp/review/request/geo_point.rb",
    "lib/yelp/review/request/location.rb",
    "pkg/yelp-0.0.2.gem",
    "pkg/yelp-0.0.2.tar.gz",
    "pkg/yelp-0.0.2/CHANGELOG.rdoc",
    "pkg/yelp-0.0.2/LICENSE.txt",
    "pkg/yelp-0.0.2/Manifest",
    "pkg/yelp-0.0.2/Manifest.txt",
    "pkg/yelp-0.0.2/README.rdoc",
    "pkg/yelp-0.0.2/Rakefile",
    "pkg/yelp-0.0.2/TODO.txt",
    "pkg/yelp-0.0.2/lib/yelp.rb",
    "pkg/yelp-0.0.2/lib/yelp/client.rb",
    "pkg/yelp-0.0.2/lib/yelp/neighborhood/request/base.rb",
    "pkg/yelp-0.0.2/lib/yelp/neighborhood/request/geo_point.rb",
    "pkg/yelp-0.0.2/lib/yelp/neighborhood/request/location.rb",
    "pkg/yelp-0.0.2/lib/yelp/phone/request/number.rb",
    "pkg/yelp-0.0.2/lib/yelp/record.rb",
    "pkg/yelp-0.0.2/lib/yelp/request.rb",
    "pkg/yelp-0.0.2/lib/yelp/response_format.rb",
    "pkg/yelp-0.0.2/lib/yelp/review/request/base.rb",
    "pkg/yelp-0.0.2/lib/yelp/review/request/bounding_box.rb",
    "pkg/yelp-0.0.2/lib/yelp/review/request/geo_point.rb",
    "pkg/yelp-0.0.2/lib/yelp/review/request/location.rb",
    "pkg/yelp-0.0.2/test/test_client.rb",
    "pkg/yelp-0.0.2/test/test_neighborhood_search.rb",
    "pkg/yelp-0.0.2/test/test_phone_search.rb",
    "pkg/yelp-0.0.2/test/test_review_search.rb",
    "pkg/yelp-0.0.2/test/yelp_helper.rb",
    "pkg/yelp-0.0.2/yelp.gemspec",
    "test/test_client.rb",
    "test/test_neighborhood_search.rb",
    "test/test_phone_search.rb",
    "test/test_review_search.rb",
    "test/yelp_helper.rb"
  ]
  s.homepage = %q{http://github.com/danengle/yelp}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{The yelp rubygem provides a Ruby object-oriented interface to the Yelp}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

